# Generated by Django 5.1.4 on 2024-12-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
