# Generated by Django 5.1.4 on 2024-12-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_contact_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='deskription_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='deskription_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='deskription_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
