# Generated by Django 5.1.4 on 2025-01-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_about_deskription_en_about_deskription_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('current_temp', models.CharField(max_length=100)),
                ('desk', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('pressure', models.CharField(max_length=100)),
                ('sunrise1', models.CharField(max_length=100)),
                ('sunrise2', models.CharField(max_length=100)),
                ('sunset1', models.CharField(max_length=100)),
                ('sunset2', models.CharField(max_length=100)),
            ],
        ),
    ]
