# Generated by Django 5.1.4 on 2025-01-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_prayer_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='time',
        ),
        migrations.AddField(
            model_name='prayer',
            name='asr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='bomdod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='peshin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='quyosh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='shom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='xufton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
