# Generated by Django 5.1.4 on 2026-02-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0007_weather_current_temp2_weather_day_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RamadanCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('week_day', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('saharlik', models.TimeField()),
                ('iftorlik', models.TimeField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramadan_days', to='myportfolio.region')),
            ],
            options={
                'ordering': ['region', 'day'],
                'unique_together': {('region', 'day', 'date')},
            },
        ),
    ]
